config/routes.rb
DemoCloud::Application.routes.draw do 
  
  mount Forem::Engine, :at => "/cloudforum" 
  resources :messages do
    get 'subject', :on => :member
    get 'forward', :on => :member
    get 'reply', :on => :member

  end


  resources :videos

  resources :admin_grades

  get "messages/index"
  match '/admin_grades', :to =>'admin_grades#index'
  resources :events

  get "password_resets/new"
  match '/calender_asses', :to =>'assignments#calender_asses'
  match '/calender_asses/filter', :to =>'assignments#filter'
  
  match '/change_password', :controller => 'users', :action => 'change_password'
   
   resources :calenders, :only => [:index] do
     get 'view_assignment', :on => :member
   end
   
   match '/courses/:id/subject', :to => "courses#subject"
   resources :courses do
     match '/check_assignments', :to =>'course_classes#check_assignments'
     resources :course_classes do
       
       
     end
     resources :student_infos do
          match '/check_student', :to =>'student_infos#check_student', on: :collection
          get 'student', :on => :member
    end
     resources :assignments do
       match 'student', :to => "assignments#student"
       match 'student/:id/submit_assignment', :to => "assignments#submit_assignment"
       match '/questions/:id/correct_answer', :to => "questions#correct_answer"
       resources :questions do
         match '/sub_questions/:id/correct_answer', :to => "sub_questions#correct_answer"
        resources :sub_questions
     
       end
     end 
     
   end

    resources :users do
      member do
        post :update_meta
      end
      collection do 
        get :course_index
        post :update_iid
        post :create_student_info
      end
    end   
    resources :institutions
    resources :sessions, :only => [:new,:create,:destroy,:edit]
    root :to => 'sessions#new'
    match 'dashboard' => 'users#dashboard', :as => 'user_root'
    match '/signup', :to =>'users#new'
    match '/signin', :to =>'sessions#new'
    match  '/users/:id/edit',  :to => "users#edit" 
    match '/signout', :to =>'sessions#destroy'
    match '/user/signout', :to =>'sessions#user_signout', :via => :post
   resources :password_resets
    match '/institutions/:id/delete', :to => "institutions#destroy"
    match '/edu_classes/check_terms', :to => "edu_classes#check_terms"
    match '/institutions/check_terms', :to => "institutions#check_terms"
    match '/edu_class/:id/status', :to => "edu_classes#toggled_status"
    match '/edu_classes/:id/delete', :to => "edu_classes#destroy"
    
    match '/units/:id/delete', :to => "units#destroy"
    match '/chapters/:id/delete', :to => "chapters#destroy"
    match '/topics/:id/delete', :to => "topics#destroy"
    match '/sub_topics/:id/delete', :to => "sub_topics#destroy"
    match '/questions/:id/delete', :to => "questions#destroy"
    match '/sub_questions/:id/delete', :to => "sub_questions#destroy"
    match '/colors/:id/delete', :to => "colors#destroy"
    match '/users/:id/delete', :to => "users#destroy"
    match '/users/:id/student', :to => "users#student"
     match '/users/:id/student/add', :to => "users#add"
     match '/users/:id/student/:id2/edit', :to => "users#edit_student", :as => :edit_student
     match '/users/:id/student/index', :to => "users#index"
     match '/users/:id/teacher', :to => "users#teacher"
     match '/users/:id/teacher/add_teacher', :to => "users#add_teacher"
     match '/users/:id/teacher/add_teacher/:id2/edit_teacher', :to => "users#edit_teacher", as: :edit_teacher
     match '/student_class/check_student_class', :to => "student_classes#check_student_class"
     match '/student_class/toggled_status', :to => "student_classes#toggled_status"
     match '/student_class', :to => "student_classes#index"
     match '/users/validations/check_email', :to=>"users#check_email"
     match '/users/validations/check_username', :to=>"users#check_username"
     match '/users/:subject_id/student_info/new/', :to=>"users#new_student_info", as: :course_new_student_info

     match '/password_resets/validations/check_pass_reset', :to=>"password_resets#check_pass_reset"
     
     match '/users/dashboard/confirm_destroy', :to => "users#confirm_destroy"
     
      match '/users/dashboard/confirm_setting', :to => "users#confirm_setting"
       match '/users/dashboard/setting', :to => "users#setting"
     
   match '/edu_classes/:edu_class_id/assignments/:id/delete', :to => "assignments#destroy"
   match '/edu_classes/:edu_class_id/assignments/:assignment_id/questions/:id/delete', :to => "questions#destroy"
   match '/edu_classes/:edu_class_id/assignments/:assignment_id/questions/:question_id/sub_questions/:id/delete', :to => "sub_questions#destroy"
     #add institute
      match '/users/:id/institute', :to => "users#institute"
      match '/users/:id/institute/add_institute', :to => "users#add_institute"
      match '/users/:id/institute/add_institute/:id2/edit_institute', :to => "users#edit_institute", as: :edit_institute
     resources :edu_classes do
       get :students, :on => :member
       get :teachers, :on => :member
     
      end
   
   match '/assignments/check_duedate', :to => "assignments#check_duedate"
   match '/assignments/check_unit', :to => "assignments#check_unit"
   match '/assignments/check_chapter', :to => "assignments#check_chapter"
   match '/assignments/check_topic', :to => "assignments#check_topic"
   match '/assignments/check_subtopic', :to => "assignments#check_subtopic"
   match '/assignments/pdf_upload', :to => "assignments#pdf_upload"
   
   match '/student/:id/check_assignment/:assignment_id', :to => "student_infos#check_assignment"
   
   match '/student/:id/result/:assignment_id', :to => "student_infos#result", :via => :post
   
   match '/staffs/check_class', :to => "staffs#check_class"
   match '/staffs/toggled_status', :to => "staffs#toggled_status"
   resources :staffs
   
   match '/subjects/check_subject', :to=>"subjects#check_subject"
   match '/subjects/:id/delete', :to => "subjects#destroy"
   resources :subjects do
    member do
      post :check_terms
    end
   end
    match '/units/check_subject', :to => "units#check_unit"
    match '/units/:id/delete', :to => "units#destroy"

   resources :units 
   match '/chapters/check_chapter', :to => "chapters#check_chapter"
   match '/chapters/:id/delete', :to => "chapters#destroy"
   resources :chapters
   match '/topics/check_topic', :to => "topics#check_topic"
    match '/topics/:id/delete', :to => "topics#destroy"
   resources :topics
   match '/sub_topics/check_subtopic', :to => "sub_topics#check_subtopic"
   match '/sub_topics/:id/delete', :to => "sub_topics#destroy"
   resources :sub_topics
   
   resources :student_assignments do
     resources :assign_ques
     resources :solve_pdf_assignments
   end
   
  
                                     
   
   resources :colors
    post '/class_settings/update', :to => "class_settings#update"
    post '/class_settings/update_color', :to => "class_settings#update_color"
    post '/class_settings/update_remainder', :to => "class_settings#update_remainder"

    namespace :admin do
    resources :people, only:[] do
      collection do
        match ':type', action: "index", as: 'index'
        match '/student_show/:id', action: "student_show", as: 'student_show'
      end
      
    end
  end
   
  end

app/models/institution.rb
class Institution < ActiveRecord::Base
   attr_accessible :Name, :Address,:Email,:user_id, :terms, :year, :sem
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_filter  :authenticate ,:only => [:edit,:update,:index,:create,:new]
   
    def index
      
       @institutions = Institution.all.paginate  :page => params[:page],:per_page => 10
         
      
    end


  def new
     @institution = Institution.new
  end
 
   def create
      @institution = Institution.new(params[:institution])
      if @institution.save
          redirect_to institutions_path
      else
          render :action => 'new'
      end
   end
  
  def show
    @institution = Institution.find(params[:id])
  end
  
  def edit
    @institution = Institution.find(params[:id])
  end
  
  def update
    @institution = Institution.find(params[:id])
    if @institution.update_attributes(params[:institution])
      redirect_to institutions_path
    else
      render :action => 'edit'
    end
  end  
  
  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy
    flash[:notice] = "Successfully destroyed product."
    redirect_to institutions_path
  end
  
  def check_terms
    render :update do |page|
      page.replace_html 'term', :partial => 'institutions/check_terms'
    end
  end
  
  
  private
    def authenticate
        deny_access unless signed_in?
    end
   
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_check_terms.html.erb
<% if params[:terms] == 'year' %>
<td align="right" valign="middle" class="tr_bg"><strong>Year </strong></td>
<td align="left" valign="top" class="tr_bg"><%= select_year(Date.today, :start_year => Time.now.year + 5, :end_year => Time.now.year - 95, :field_name => 'year', :prefix => "institution") %>
</td>
<% elsif params[:terms] == 'sem' %>

<td align="right" valign="middle" class="tr_bg"><strong>Semester </strong></td>
<td align="left" valign="top" class="tr_bg"><%= select("institution", "sem",  { "Fall" => "Fall", "Spring" => "Spring", "Summer" => "Summer"}) %><%= select_year(Date.today, :start_year => Time.now.year + 5, :end_year => Time.now.year - 95, :field_name => 'year', :prefix => "institution") %>
</td>
<% end %>

app/views/institutions/_form.html.erb
<div class="mc_heading">
	Institutions
	
	</div>





	<div class="row4">
	<%= form_for(@institution) do |f| %>
	<table width="100%" border="0" align="center" cellpadding="10" cellspacing="2"> 
	<tbody>
	  
	<tr>
		<td align="right" valign="middle" class="tr_bg"><strong>Name </strong></td>
    	<td align="left" valign="top" class="tr_bg">
    	<%= f.text_field :Name,:class=>"textfield3"  %>
    	</td>
    	</tr>
		
	
   
		
	<tr>
		<td align="right" valign="middle" class="tr_bg"><strong>Address </strong></td>
    	<td align="left" valign="top" class="tr_bg"><%= f.text_area :Address,:rows =>4 ,:class=>"textfield3" %></td>
  </tr>
		
	<tr>
		<td align="right" valign="middle" class="tr_bg"><strong>Email </strong></td>
    	<td align="left" valign="top" class="tr_bg"><%= f.text_field :Email ,:class=>"textfield3" %></td>
    	 <%= f.hidden_field :user_id, :value => current_user.id %>
    	
    	 
       
    	</tr>
    	
       <tr>
          		<td align="right" valign="middle" class="tr_bg"><strong>Terms </strong></td>
              <td align="left" valign="top" class="tr_bg"><%= f.select( :terms,  { "Year" => "year", "Semester" => "sem"}, {:prompt => 'Select'}, {:onChange => "#{remote_function(:url => {:controller =>"institutions", :action => "check_terms"}, :with => "'terms='+value")}"}) %></td>
        </tr>
  
  <tr id="term">
      
  </tr>
		
	
		
	<tr>
	  <td colspan="2" align="left" valign="middle" class="tr_bg" style="padding-left:290px"><%= f.submit "Save",  :class=>"greenbutton", :style=>"float:left" %> </td>
	  </tr>
</tbody></table>
	
	<%end%>
	</div>

app/views/institutions/edit.html.erb
<div class="mc_heading">
	Institutions
	
	</div>





	<div class="row4">
	<%= form_for(@institution) do |f| %>
	<table width="100%" border="0" align="center" cellpadding="10" cellspacing="2"> 
	<tbody>
	  
	<tr>
		<td align="right" valign="middle" class="tr_bg"><strong>Name </strong></td>
    	<td align="left" valign="top" class="tr_bg">
    	<%= f.text_field :Name,:size =>20 %>
    	</td>
    	</tr>
		
	
   
		
	<tr>
		<td align="right" valign="middle" class="tr_bg"><strong>Address </strong></td>
    	<td align="left" valign="top" class="tr_bg"><%= f.text_area :Address,:rows =>4 ,:class=>"textfield3" %></td>
    	</tr>
		
	<tr>
		<td align="right" valign="middle" class="tr_bg"><strong>Email </strong></td>
    	<td align="left" valign="top" class="tr_bg"><%= f.text_field :Email,:size =>15 ,:class=>"textfield3" %></td>
    	 <%= f.hidden_field :user_id, :value => current_user.id %>
    	</tr>
		
	
		  <tr>
        		<td align="right" valign="middle" class="tr_bg"><strong>Terms </strong></td>
            <td align="left" valign="top" class="tr_bg"><%= f.select( :terms,  { "Year" => "year", "Semester" => "sem"}, {:prompt => 'Select'}, {:onChange => "#{remote_function(:url => {:controller =>"institutions", :action => "check_terms"}, :with => "'terms='+value")}"}) %></td>
      </tr>

      <tr id="term">
        <% if @institution.terms == 'year' %>
          <td align="right" valign="middle" class="tr_bg"><strong>Year </strong></td>
          <td align="left" valign="top" class="tr_bg"><%= select_year(@institution.year, :start_year => Time.now.year + 5, :end_year => Time.now.year - 95, :field_name => 'year', :prefix => "institution") %>
          </td>
          
        <% elsif @institution.terms == 'sem' %> 
          <td align="right" valign="middle" class="tr_bg"><strong>Semester </strong></td>
          <td align="left" valign="top" class="tr_bg"><%= select("institution", "sem",  { "Fall" => "Fall", "Spring" => "Spring", "Summer" => "Summer"}) %><%= select_year(@institution.year, :start_year => Time.now.year + 5, :end_year => Time.now.year - 95, :field_name => 'year', :prefix => "institution") %>
          </td>
        <% end %>
      </tr>
	<tr>
	  <td colspan="2" align="left" valign="middle" class="tr_bg" style="padding-left:290px"><%= f.submit "Update",  :class=>"greenbutton", :style=>"float:left" %> </td>
	  </tr>
</tbody></table>
	
	<%end%>
	</div>

app/views/institutions/index.html.erb
  <div class="mc_heading">
	Manage Institutions
	
	</div>

   <div style="margin-bottom:10px; width:100%; height:auto; float:left">
	<div style="float:left; width:50%; height:auto; text-align:left">
	<img src="/assets/add.png" alt="" width="24" height="24" border="0" align="absmiddle" /><%= link_to 'Add New Institution', new_institution_path,:class=>"table_heading_link" %></div>
	 </div> 
	
	 <div class="row4">
 	<table width="100%" border="0" align="center" cellpadding="5" cellspacing="2"> 
	<tbody><tr class="pretty"> <th align="center" valign="top" class="table_heading">Name</th>
		<th align="center" valign="top" class="table_heading">Address</th>
	    <th align="center" valign="top" class="table_heading">Email</th>
	   
	    <th width="37%" colspan="3" align="center" valign="top" class="table_heading">Action</th>
	    
	</tr>
	
		      

	
		<% @institutions.each do |institution| %>
		
		 <tr>
       <td align="left" valign="top" class="tr_bg"><%= institution.Name %></td>
   	<td align="left" valign="top" class="tr_bg"><%= institution.Address%> </td>
       <td align="left" valign="top" class="tr_bg"><%= institution.Email%> </td>
   	
       <td align="left" valign="middle" class="tr_bg">
      <%= link_to 'Show', institution,:class =>"td_link" %>|<%= link_to 'Edit', edit_institution_path(institution),:class =>"td_link" %>|<a href="/institutions/<%= institution.id %>/delete" class ="td_link"  onclick="if(confirm('Are you sure you want to delete this page?'))  return true;  else  return false;" class = "icon-3 info-tooltip" >Delete</a> </td>
       </td>
      </tr>

   <% end %>
 </tbody></table>
		 <%= will_paginate @institutions %>
</div>		
		
		
		
		
		
		
		

app/views/institutions/new.html.erb
<%= render 'form' %>

app/views/institutions/show.html.erb
<div class="mc_heading">
	Institutions
	
	</div>
	
	
	

	
		
	<div class="row4">
	
	<table width="100%" border="0" align="center" cellpadding="10" cellspacing="2"> 
	<tbody>
		
	<tr>
		<td width="50%" align="right" valign="middle" class="tr_bg"><strong>Name</strong></td>
    	<td align="left" valign="top" class="tr_bg"><label><%= @institution.Name %></label></td>
    	</tr>
		
	<tr>
	  <td width="50%" align="right" valign="middle" class="tr_bg"><strong>Address</strong></td>
	  <td align="left" valign="top" class="tr_bg"><%= @institution.Address%></td>
	  </tr>
	
		
	<tr>
		<td width="50%" align="right" valign="middle" class="tr_bg"><strong>Email </strong></td>
    	<td align="left" valign="top" class="tr_bg"><%= @institution.Email%></td>
    	</tr>
		
	
	  
</tbody></table>
	
	
	</div>
	































 


 