config/routes.rb
DemoCloud::Application.routes.draw do 
  
  mount Forem::Engine, :at => "/cloudforum" 
  resources :messages do
    get 'subject', :on => :member
    get 'forward', :on => :member
    get 'reply', :on => :member

  end


  resources :videos

  resources :admin_grades

  get "messages/index"
  match '/admin_grades', :to =>'admin_grades#index'
  resources :events

  get "password_resets/new"
  match '/calender_asses', :to =>'assignments#calender_asses'
  match '/calender_asses/filter', :to =>'assignments#filter'
  
  match '/change_password', :controller => 'users', :action => 'change_password'
   
   resources :calenders, :only => [:index] do
     get 'view_assignment', :on => :member
   end
   
   match '/courses/:id/subject', :to => "courses#subject"
   resources :courses do
     match '/check_assignments', :to =>'course_classes#check_assignments'
     resources :course_classes do
       
       
     end
     resources :student_infos do
          match '/check_student', :to =>'student_infos#check_student', on: :collection
          get 'student', :on => :member
    end
     resources :assignments do
       match 'student', :to => "assignments#student"
       match 'student/:id/submit_assignment', :to => "assignments#submit_assignment"
       match '/questions/:id/correct_answer', :to => "questions#correct_answer"
       resources :questions do
         match '/sub_questions/:id/correct_answer', :to => "sub_questions#correct_answer"
        resources :sub_questions
     
       end
     end 
     
   end

    resources :users do
      member do
        post :update_meta
      end
      collection do 
        get :course_index
        post :update_iid
        post :create_student_info
      end
    end   
    resources :institutions
    resources :sessions, :only => [:new,:create,:destroy,:edit]
    root :to => 'sessions#new'
    match 'dashboard' => 'users#dashboard', :as => 'user_root'
    match '/signup', :to =>'users#new'
    match '/signin', :to =>'sessions#new'
    match  '/users/:id/edit',  :to => "users#edit" 
    match '/signout', :to =>'sessions#destroy'
    match '/user/signout', :to =>'sessions#user_signout', :via => :post
   resources :password_resets
    match '/institutions/:id/delete', :to => "institutions#destroy"
    match '/edu_classes/check_terms', :to => "edu_classes#check_terms"
    match '/institutions/check_terms', :to => "institutions#check_terms"
    match '/edu_class/:id/status', :to => "edu_classes#toggled_status"
    match '/edu_classes/:id/delete', :to => "edu_classes#destroy"
    
    match '/units/:id/delete', :to => "units#destroy"
    match '/chapters/:id/delete', :to => "chapters#destroy"
    match '/topics/:id/delete', :to => "topics#destroy"
    match '/sub_topics/:id/delete', :to => "sub_topics#destroy"
    match '/questions/:id/delete', :to => "questions#destroy"
    match '/sub_questions/:id/delete', :to => "sub_questions#destroy"
    match '/colors/:id/delete', :to => "colors#destroy"
    match '/users/:id/delete', :to => "users#destroy"
    match '/users/:id/student', :to => "users#student"
     match '/users/:id/student/add', :to => "users#add"
     match '/users/:id/student/:id2/edit', :to => "users#edit_student", :as => :edit_student
     match '/users/:id/student/index', :to => "users#index"
     match '/users/:id/teacher', :to => "users#teacher"
     match '/users/:id/teacher/add_teacher', :to => "users#add_teacher"
     match '/users/:id/teacher/add_teacher/:id2/edit_teacher', :to => "users#edit_teacher", as: :edit_teacher
     match '/student_class/check_student_class', :to => "student_classes#check_student_class"
     match '/student_class/toggled_status', :to => "student_classes#toggled_status"
     match '/student_class', :to => "student_classes#index"
     match '/users/validations/check_email', :to=>"users#check_email"
     match '/users/validations/check_username', :to=>"users#check_username"
     match '/users/:subject_id/student_info/new/', :to=>"users#new_student_info", as: :course_new_student_info

     match '/password_resets/validations/check_pass_reset', :to=>"password_resets#check_pass_reset"
     
     match '/users/dashboard/confirm_destroy', :to => "users#confirm_destroy"
     
      match '/users/dashboard/confirm_setting', :to => "users#confirm_setting"
       match '/users/dashboard/setting', :to => "users#setting"
     
   match '/edu_classes/:edu_class_id/assignments/:id/delete', :to => "assignments#destroy"
   match '/edu_classes/:edu_class_id/assignments/:assignment_id/questions/:id/delete', :to => "questions#destroy"
   match '/edu_classes/:edu_class_id/assignments/:assignment_id/questions/:question_id/sub_questions/:id/delete', :to => "sub_questions#destroy"
     #add institute
      match '/users/:id/institute', :to => "users#institute"
      match '/users/:id/institute/add_institute', :to => "users#add_institute"
      match '/users/:id/institute/add_institute/:id2/edit_institute', :to => "users#edit_institute", as: :edit_institute
     resources :edu_classes do
       get :students, :on => :member
       get :teachers, :on => :member
     
      end
   
   match '/assignments/check_duedate', :to => "assignments#check_duedate"
   match '/assignments/check_unit', :to => "assignments#check_unit"
   match '/assignments/check_chapter', :to => "assignments#check_chapter"
   match '/assignments/check_topic', :to => "assignments#check_topic"
   match '/assignments/check_subtopic', :to => "assignments#check_subtopic"
   match '/assignments/pdf_upload', :to => "assignments#pdf_upload"
   
   match '/student/:id/check_assignment/:assignment_id', :to => "student_infos#check_assignment"
   
   match '/student/:id/result/:assignment_id', :to => "student_infos#result", :via => :post
   
   match '/staffs/check_class', :to => "staffs#check_class"
   match '/staffs/toggled_status', :to => "staffs#toggled_status"
   resources :staffs
   
   match '/subjects/check_subject', :to=>"subjects#check_subject"
   match '/subjects/:id/delete', :to => "subjects#destroy"
   resources :subjects do
    member do
      post :check_terms
    end
   end
    match '/units/check_subject', :to => "units#check_unit"
    match '/units/:id/delete', :to => "units#destroy"

   resources :units 
   match '/chapters/check_chapter', :to => "chapters#check_chapter"
   match '/chapters/:id/delete', :to => "chapters#destroy"
   resources :chapters
   match '/topics/check_topic', :to => "topics#check_topic"
    match '/topics/:id/delete', :to => "topics#destroy"
   resources :topics
   match '/sub_topics/check_subtopic', :to => "sub_topics#check_subtopic"
   match '/sub_topics/:id/delete', :to => "sub_topics#destroy"
   resources :sub_topics
   
   resources :student_assignments do
     resources :assign_ques
     resources :solve_pdf_assignments
   end
   
  
                                     
   
   resources :colors
    post '/class_settings/update', :to => "class_settings#update"
    post '/class_settings/update_color', :to => "class_settings#update_color"
    post '/class_settings/update_remainder', :to => "class_settings#update_remainder"

    namespace :admin do
    resources :people, only:[] do
      collection do
        match ':type', action: "index", as: 'index'
        match '/student_show/:id', action: "student_show", as: 'student_show'
      end
      
    end
  end
   
  end

app/controllers/course_classes_controller.rb
class CourseClassesController < ApplicationController
  before_filter  :authenticate ,:only => [:index, :check_assignments]
  helper_method :sort_column, :sort_direction
  
  layout 'courses'
  
  def index
    @assignments = Assignment.order(sort_column + " " + sort_direction).find_all_by_subject_id(params[:course_id], :conditions => ['name LIKE ?', "%#{params[:search]}%"])
    if ( current_user.role? :admin) || (current_user.role? :instituteadmin )
      @subjects = Subject.all #change -- Subject.find_all_by_class_id(params[:class_id])
    else
      @subjects = current_user.subjects
    end
  end
  
  def check_assignments
    @assignments = Assignment.find_all_by_subject_id(params[:course_id])
    
    render :update do |page|
        page.replace_html 'box_bg', :partial => 'course_classes/assignments'
    end
    
  end
  
  
  
  private
    def authenticate
        deny_access unless signed_in?
    end
    
     def sort_column
      Assignment.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
  
end

app/helpers/course_classes_helper.rb
module CourseClassesHelper
end

app/views/course_classes/_assignments.html.erb
 <% unless current_user.role?("student")%>
 <div class="assignment_new_link">
    <img src="/assets/add.png" alt="" width="24" height="24" border="0" align="absmiddle"/> 
    <%= link_to 'New', new_course_assignment_path(params[:course_id]), :remote => true %> 
</div> 
<% end %>
<div class="assignment_heading"> Assignment</div>
           <div class="points_heading">Points</div>
           <div class="due_heading">Due</div>	

<%  @assignments.each_with_index do |assignment,i| %>
<div class="pink_bg" style="background: <%= current_user.get_color_for(assignment.subject_id) %>">

<% if (current_user.role? :student ) %>
  
    <% solve = SolvedStudent.find_by_assignment_id_and_user_id(assignment.id,current_user.id)  %>
    <% unless solve.nil? %>
    
      <div class="sn"><input type="checkbox" class="field checkbox" name="Field3" id="Field3" DISABLED checked=""><label></label><%= (i+1) %>. </div>
      <div class="icondiv"></div>

		
        <div class="assignment">
        	<% if assignment.assignment_type == "reading"%>a
        	<%= link_to assignment.name, new_student_assignment_solve_pdf_assignment_path(assignment.id) ,:remote=> true%>
       		<% elsif assignment.assignment_type == "exercise"%>
        	<%= link_to assignment.name, new_student_assignment_assign_que_path(assignment.id), :remote=>true %>
     		<% end %>
       </div>
        <div class="points">10 /10</div>
       <div class="due"><%= assignment.due_date.strftime('%m / %d ' )%></div>
    
     <% else %>
     
      <div class="sn"><input type="checkbox" class="field checkbox" name="Field3" id="Field3" DISABLED><label></label><%= (i+1) %>. </div>
      <div class="icondiv"></div>

	<% if assignment.assignment_type == "reading"%>
	<div class="assignment"><%= link_to assignment.name, new_student_assignment_solve_pdf_assignment_path(assignment.id) ,:remote=>true %></div>
       		<% elsif assignment.assignment_type == "exercise"%>
        <div class="assignment"><%= link_to assignment.name, new_student_assignment_assign_que_path(assignment.id), :remote=>true %></div>
        <% end %>
        <div class="points">10 /10</div>
       <div class="due"><%= assignment.due_date.strftime('%m / %d ' )%></div>
     
     <% end %>
  


       <% else %>
<div class="sn"><input type="checkbox" class="field checkbox" name="Field3" id="Field3"><label></label><%= (i+1) %>. </div>
<div class="icondiv"></div>     
  
 <div class="assignment">
        	<% if assignment.assignment_type == "reading"%>
        	<%= link_to assignment.name, new_student_assignment_solve_pdf_assignment_path(assignment.id) ,:remote => "true"%>
       		<% elsif assignment.assignment_type == "exercise"%>
        	<%= link_to assignment.name, new_student_assignment_assign_que_path(assignment.id), :remote=>true %>
     		<% end %>
       </div>
<div class="points">10 /10</div>
<div class="due"><%= assignment.due_date.strftime('%m / %d ' )%></div>
<div class="checkbox2"><input name="" type="checkbox" value="" /></div>

<% end %>
</div>
<% end %>

app/views/course_classes/index.html.erb
<% content_for :styles do %>
 <%= stylesheet_link_tag "tab" %>
 <%= stylesheet_link_tag "subject2" %>
 <%= stylesheet_link_tag "facebox" %>
<% end %>

<% content_for :scripts do %>
  <%= javascript_include_tag "facebox" %>
<% end %>

<!-- Include Mootools and FancySelect -->
	<script type='text/javascript'>
			jQuery(document).ready(function() {
				enableSelectBoxes();
			});
			
			function enableSelectBoxes(){
				jQuery('div.selectBox').each(function(){
					
					jQuery(this).attr('value',jQuery(this).children('div.selectOptions').children('span.selectOption:first').attr('value'));
					
					jQuery(this).children('span.selected,span.selectArrow').click(function(){
						if(jQuery(this).parent().children('div.selectOptions').css('display') == 'none'){
							jQuery(this).parent().children('div.selectOptions').css('display','block');
						}
						else
						{
							jQuery(this).parent().children('div.selectOptions').css('display','none');
						}
					});
					
					jQuery(this).find('span.selectOption').click(function(){
						jQuery(this).parent().css('display','none');
						jQuery(this).closest('div.selectBox').attr('value',jQuery(this).attr('value'));
						jQuery(this).parent().siblings('span.selected').html(jQuery(this).html());
					});
				});				
			}//-->
		</script>
		
<div id="row2">
	
	
 <div id="row2_left">

   <div>
  		<div style="float:left; margin:0 0 0 0px">

  			<div class='selectBox'>
  				<span class='selected'>
  				  <% sel_subject = Subject.find(params[:course_id]) %>
  				  
  				   <style type="text/css">
   					.<%= sel_subject.name %>_subject{ background: url(/assets/transperant_button.png); padding:10px; text-align:center; border-radius:5px; border:1px solid #e4bd86; width:178px; height:68px}
             .<%= sel_subject.name %>_subject:hover{ background:; border:1px solid #989898; box-shadow: 0px 0px 7px #ffc600;}
             .<%= sel_subject.name %>_subject:active{ background:; border:1px solid #989898; box-shadow: 0px 0px 7px #ffc600;}
   					</style>
  			 
  			     <a href="javascript:void(0);", data-remote="true" style="text-decoration:none; color:#6C6C6C">
              <div class="<%= sel_subject.name %>_subject">
             		<div class="subject"><%= sel_subject.name %></div>
             		<div><%= sel_subject.class_location rescue ""%></div>
             		<div><%= sel_subject.start_time.strftime("%l:%M %P") rescue ""%>-<%= sel_subject.end_time.strftime("%l:%M %P") rescue ""%></div>
             	</div>
             </a>
  				</span>
  				<div class="selectOptions">
  				 <% @subjects.each do |subject| %>
  					
  					<style type="text/css">
  					.<%= subject.name %>_subject{ background: url(/assets/transperant_button.png); padding:10px; text-align:center; border-radius:5px; border:1px solid #e4bd86; width:178px; height:68px}
            .<%= subject.name %>_subject:hover{ background:; border:1px solid #989898; box-shadow: 0px 0px 7px #ffc600;}
            .<%= subject.name %>_subject:active{ background:; border:1px solid #989898; box-shadow: 0px 0px 7px #ffc600;}
  					</style>
  					
  					<span class="selectOption" value="Option 1">
             <a href="<%= course_check_assignments_path(subject.id) %>", data-remote="true" style="text-decoration:none; color:#6C6C6C">
               <div class="<%= subject.name %>_subject">
             		  <div class="subject"><%= subject.name %></div>
             		  <div><%= subject.class_location rescue ""%></div>
             		  <div><%= subject.start_time.strftime("%l:%M %P") rescue ""%>-<%= subject.end_time.strftime("%l:%M %P") rescue ""%></div>
             	 </div>
              </a>
            </span>
  				 <% end %>
  				</div>
  			</div>

  		</div>
  	</div>
  	

    <div><a class="left_button" href="#">Syllabus</a></div> 
    <div><%= link_to "Assignment", {:controller=>"course_classes", :action=>"index", :course_id=>"#{params[:course_id]}"}, :class=>"left_button_selected" %></div> 
    <div class="forum_link"><%= link_to 'Forum',forem.forum_path(sel_subject.forum.id), :remote => true, class: "left_button" %></div> 
	<div class="resources_link"><%= link_to 'Resources', {:controller=>"videos", :action=>"index", :course_id=>"#{params[:course_id]}"}, :remote => true, class: "left_button" %></div> 

    <div style="width:300px; height:auto; float:left; padding:100px 0 0 20px">Grades</div>
    <div><a class="left_button" href="#">Grade History</a></div>


  </div>
<!--tab start-->
<div id="row1_right">

<div id="container">
		
		
		<div class="tabdiv">
		
		  <% if params[:sort].nil? %>
		  <%= link_to "", {:controller=>"course_classes", :action=>"index", :course_id=>"#{sel_subject.id}", :class_id=>"#{params[:class_id]}"}, :class=>"tab_all_selected" %>
		  <% else %>
		  <%= link_to "", {:controller=>"course_classes", :action=>"index", :course_id=>"#{sel_subject.id}", :class_id=>"#{params[:class_id]}"}, :class=>"tab_all" %>
		  <% end %>
		  <% if params[:sort] == "due_date" %>
		    <%= sortable "assignment_type", "", "tab_date_selected" %>
		  <% else %> 
		    <%= sortable "due_date", "", "tab_date" %>
		  <% end %>
		  
		  <% if params[:sort] == "assignment_type" %>
		    <%= sortable "assignment_type", "", "type_tab_selected" %>
		  <% else %> 
		    <%= sortable "assignment_type", "", "type_tab" %>
		  <% end %> 
		</div>
		
    <div class="search" style="width:240px !important; top: 38px !important; position: relative !important;">
			<%= form_tag course_course_classes_path, :method => 'get' do %>
 			 <%= text_field_tag :search, params[:search],:class=>"searchfield", :placeholder => "Search.." %>
			<%# hidden_field_tag :class_id, "#{sel_subject.class_id}" %>
 			 <div style="width:32px; float:right; position:relative;top: -32px;
left: -39px;"><%= submit_tag "", :name => nil, :class=>"search_courses" %></div>
	
	    <% end %>
	    
    </div>
    
    
    		
  </div>
  
		<span class="clear"></span>
		<div class="content all">
		<div id="row2_right" class="assignments_container">
      

        <div id="box_bg" class="scrollable_list assignment_list" >
        	
            <%= render "assignments" %>
        </div>
      
    </div>
    

    </div>
		</div>
	</div>
</div>
<!--tab end-->

<script type="text/javascript" src="js/tabs.js"></script>



	</div>
	

app/views/course_classes/show.html.erb
<% content_for :styles do %>
 <%= stylesheet_link_tag "tab" %>
 <%= stylesheet_link_tag "facebox" %>
<% end %>

<% content_for :scripts do %>
  <%= javascript_include_tag "facebox" %>
<% end %>

<!-- Include Mootools and FancySelect -->
	<script type='text/javascript'>
			jQuery(document).ready(function() {
				enableSelectBoxes();
			});
			
			function enableSelectBoxes(){
				jQuery('div.selectBox').each(function(){
					
					jQuery(this).attr('value',jQuery(this).children('div.selectOptions').children('span.selectOption:first').attr('value'));
					
					jQuery(this).children('span.selected,span.selectArrow').click(function(){
						if(jQuery(this).parent().children('div.selectOptions').css('display') == 'none'){
							jQuery(this).parent().children('div.selectOptions').css('display','block');
						}
						else
						{
							jQuery(this).parent().children('div.selectOptions').css('display','none');
						}
					});
					
					jQuery(this).find('span.selectOption').click(function(){
						jQuery(this).parent().css('display','none');
						jQuery(this).closest('div.selectBox').attr('value',jQuery(this).attr('value'));
						jQuery(this).parent().siblings('span.selected').html(jQuery(this).html());
					});
				});				
			}//-->
		</script>
		
<div id="row2">
	
	
 <div id="row2_left">

   <div>
  		<div style="float:left; margin:0 0 0 0px">

  			<div class='selectBox'>
  				<span class='selected'>
  				  <% sel_subject = Subject.find(params[:course_id]) %>
  				  <a href="javascript:void(0);" data-remote="true">
              <img style="float:left; background:url('/assets/avatar.png') no-repeat scroll center 13px <%= current_user.get_color_for(sel_subject.id) %>;" src="/assets/avatar.png" class="english_attendance">
              
              <span style="float:left; padding:35px 0 0 10px"><%= sel_subject.name %></span>
            </a>
  				</span>
  				<div class="selectOptions" >
  				 <% @subjects.each do |subject| %>
  					<span class="selectOption" value="Option 1">
  					<a href="<%= course_check_assignments_path(subject.id) %>", data-remote="true">
  					<img style="float:left; background:url('/assets/avatar.png') no-repeat scroll center 13px <%= current_user.get_color_for(subject.id) %>;" src="/assets/avatar.png" class="english_attendance">
  					<span style="float:left; padding:35px 0 0 10px"><%= subject.name %></span>
  					</a>
  					</span>
  				 <% end %>
  				</div>
  			</div>

  		</div>
  	</div>
  	

    <div><a class="left_button" href="#">Syllabus</a></div> 
    <div><a class="left_button" href="#">Assignment</a></div> 
    <div><a class="left_button" href="#">Contacts</a></div> 

    <div style="width:300px; height:auto; float:left; padding:150px 0 0 20px">Grades</div>
    <div><a class="left_button" href="#">Grade History</a></div>


  </div>
<!--tab start-->
<div id="row1_right">

<div id="container">
		<ul class="menu">
			<li id="all" style="border-radius: 10px 0 0 10px;"><%= link_to "All", {:controller=>"course_classes", :action=>"index", :course_id=>"#{sel_subject.id}", :class_id=>"#{sel_subject.class_id}"} %></li>
			<li id="date" style="border-radius:0px;"><%= sortable "due_date", "Date" %></li>
			<li id="type" style="border-radius: 0 10px 10px 0;"><%= sortable "assignment_type", "Type" %></li>
		</ul>
		
    <div class="search" style="width:240px !important;">
			<%= form_tag course_course_classes_path, :method => 'get' do %>
 			 <%= text_field_tag :search, params[:search],:class=>"searchfield" %>
			<%= hidden_field_tag :class_id, "#{sel_subject.class_id}" %>
			 <div style="width:32px; float:right; position:relative;top:-35px"><%= submit_tag "", :name => nil, :class=>"search_courses" %></div>
	
	    <% end %>
	    
    </div>
    
    
    		
  </div>
  
		<span class="clear"></span>
		<div class="content all">
		<div id="row2_right">
      <div id="topcurve"></div>

        <div id="box_bg">
        	
            <%= render "assignments" %>
        </div>
    </div>
    <div id="bottom_curve"></div>

    </div>
		</div>
	</div>
</div>
<!--tab end-->

<script type="text/javascript" src="js/tabs.js"></script>



	</div>
	